// ============================================================================
// TYPE GENERATOR - Generate TypeScript type strings from AST analysis
// ============================================================================

export function generatePropsInterface(componentName: string, props: string[]): string {
  if (props.length === 0) return `interface ${componentName}Props {}`;
  const propLines = props.map(prop => prop === '{...}' ? `  // TODO: Define destructured props` : `  ${prop}?: unknown;`);
  return `interface ${componentName}Props {\n${propLines.join('\n')}\n}`;
}

export function generateParamType(paramName: string): string {
  const commonTypes: Record<string, string> = {
    event: 'React.FormEvent',
    e: 'React.ChangeEvent<HTMLInputElement>',
    props: 'Props',
    children: 'React.ReactNode',
    id: 'string | number',
    name: 'string',
    value: 'string',
    onClick: '() => void',
    onChange: '(value: string) => void',
    className: 'string',
    style: 'React.CSSProperties',
    loading: 'boolean',
    disabled: 'boolean',
    data: 'unknown',
    index: 'number',
  };
  return commonTypes[paramName] || 'unknown';
}

export function generateFileHeader(toolName: string): string {
  return `// ============================================================================
// Generated by code-modernizer: ${toolName}
// Generated at: ${new Date().toISOString()}
// ============================================================================
`;
}
