// ============================================================================
// TYPE GENERATOR - Generate TypeScript type strings from AST analysis
// ============================================================================

function inferPropType(propName: string): string {
  const n = propName.toLowerCase().replace(/[?!]/g, '');
  if (/^on[a-z]/.test(propName)) {
    if (/change/.test(n)) return '(value: string) => void';
    if (/submit/.test(n)) return '(event: React.FormEvent) => void';
    if (/keydown|keyup|keypress/.test(n)) return '(event: React.KeyboardEvent) => void';
    if (/mouse|hover/.test(n)) return '(event: React.MouseEvent) => void';
    if (/focus|blur/.test(n)) return '(event: React.FocusEvent) => void';
    return '() => void';
  }
  if (/children/.test(n)) return 'React.ReactNode';
  if (/classname|class$/.test(n)) return 'string';
  if (/style$/.test(n)) return 'React.CSSProperties';
  if (/^(label|title|text|name|placeholder|description|message|caption|heading|subtitle)$/.test(n)) return 'string';
  if (/^(id|key|slug|uid|uuid)$/.test(n)) return 'string';
  if (/href|src|url|path$|link$/.test(n)) return 'string';
  if (/type$|variant$|color$|size$|align$|justify$|position$|placement$|direction$/.test(n)) return 'string';
  if (/^(count|num|index|size|width|height|limit|offset|total|min|max|step|rows|cols|tabindex)$/.test(n)) return 'number';
  if (/^(disabled|hidden|visible|active|open|loading|checked|selected|required|readonly|autofocus|multiple|fullwidth|fullscreen|fluid|compact|inline|inverted|basic|circular|fitted|icon|labeled|negative|positive|toggle|animated|floating|pointing|scrolling|blurring|closeonescape|closeondimdisclick|dimmer)$/.test(n)) return 'boolean';
  if (/disabled$|hidden$|visible$|active$|open$|loading$|checked$|selected$|required$|readonly$|autofocus$|multiple$/.test(n)) return 'boolean';
  if (/items$|list$|options$|data$|entries$|values$|children$/.test(n)) return 'unknown[]';
  if (/ref$/.test(n)) return 'React.Ref<HTMLElement>';
  if (/^(event|e|evt)$/.test(n)) return 'React.SyntheticEvent';
  if (/rest$|props$/.test(n)) return 'Record<string, unknown>';
  return 'unknown';
}

export function generatePropsInterface(componentName: string, params: string[]): string {
  const propLines: string[] = [];

  for (const param of params) {
    // Destructured object: {label,onClick,disabled}
    if (param.startsWith('{') && param.endsWith('}')) {
      const inner = param.slice(1, -1);
      const fields = inner.split(',').map(f => f.trim()).filter(f => f && f !== '...' && f !== '...rest');
      for (const field of fields) {
        const type = inferPropType(field);
        propLines.push(`  ${field}?: ${type};`);
      }
      if (inner.includes('...rest')) {
        propLines.push('  [key: string]: unknown;');
      }
    } else if (param === '...rest' || param === '...') {
      propLines.push('  [key: string]: unknown;');
    } else if (param !== '{...}' && param !== '[...]') {
      const type = inferPropType(param);
      propLines.push(`  ${param}?: ${type};`);
    }
  }

  if (propLines.length === 0) {
    propLines.push('  // TODO: Add prop types');
  }

  return `interface ${componentName}Props {\n${propLines.join('\n')}\n}`;
}

export function generateParamType(paramName: string): string {
  return inferPropType(paramName);
}

export function generateFileHeader(toolName: string): string {
  return `// ============================================================================
// Generated by code-modernizer: ${toolName}
// ============================================================================
`;
}
